# -*- coding: utf-8 -*-
"""Randoforest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qk5TNPH7cN2ezPyGniGS33QmsywgCBh7
"""

from sklearn.ensemble import RandomForestRegressor
from fastai.metrics import accuracy,rmse
import math
class Randomforest():
  def __init__(self,n_estimators=40, min_samples_leaf=15,
        max_samples=1500, max_features=0.5, n_jobs=-1, oob_score=True,**kwargs):
    self.n_estimators=n_estimators,
    self.min_samples_leaf=min_samples_leaf,
    self.max_samples=max_samples ,
    self.max_features=max_features,
    self.n_jobs=n_jobs,
    self.oob_score=oob_score

  def model(self,x,y):
    self.m=RandomForestRegressor(n_estimators=self.n_estimators, min_samples_leaf=self.min_samples_leaf,
        max_samples=self.max_samples, max_features=self.max_features, n_jobs=self.n_jobs, oob_score=self.oob_score)
    return self.m.fit(x, y)
  
  def model_rmse(self,x,y):
    r_mse=round(math.sqrt(((pred-y)**2).mean()),6)
    r_mse1=r_mse(self.m.predict(x),y)
    r_mse2=round(rmse(self.m.predict(x),y),6)
    return r_mse1,r_mse2
  
  def model_accuracy(self,x,y):
    return accuracy(self.m.predict(x),y)